platform :ios, '15.1'

require_relative '../node_modules/react-native/scripts/react_native_pods'

prepare_react_native_project!
use_frameworks! :linkage => :static

target 'AuthNative' do # Troque pelo nome do seu target iOS
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath]
  )

  post_install do |installer|
    react_native_post_install(installer, config[:reactNativePath])
    
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      end
    end
  end
end
